In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

In [4]:
kr_sungdb = ['김', '이', '박', '최', '정', '강', '조', '윤', '장', 
             '임', '오', '한', '신', '서', '권', '황', '안', '송', '유',
             '홍', '전', '고', '문', '손', '양', '배', '조', '백', '허',
             '남', '심', '유', '노', '하', '전', '정', '곽', '성', '차',
             '구', '우', '주', '유', '나', '임', '신', '민', '진', '지',
             '엄', '원', '채', '강', '천', '양', '공', '현', '방', '변',
             '함', '노', '염', '여', '추', '변', '도', '석', '신', '소',
             '선', '주', '설', '마', '방', '길', '정', '위', '표', '연',
             '명', '기', '옥', '왕', '반', '금', '육', '진', '인', '맹',
             '제', '탁', '모', '여', '남궁', '장', '어', '유', '국', '은',
             '편', '강', '용', '구', '예', '한', '봉', '경', '소', '사',
             '부', '석', '황보', '가', '천', '복', '태', '목', '지', '형',
             '피', '계', '감', '전', '진', '음', '두', '장', '동', '온',
             '송', '경', '사공', '제갈', '호', '하', '미', '빈', '선우',
             '채', '연', '우', '설', '범', '좌', '노', '양', '갈', '반', '팽', '승', '간', '공', '상', '기', '시', '국', '위', '채', '시', '서문', '도', '강', '이', '호', '빈', '방', '진', '단', '서', '원', '견', '창', '방', '순', '당', '마', '화', '구', '이', '모', '성', '양', '종', '독고', '승', '옹', '빙', '장', '추', '편', '아', '대', '평', '궁', '도', '풍', '강', '연', '점', '섭', '견', '흥', '국', '여', '내', '낭', '제', '해', '봉', '기', '판', '궉', '초', '매', '사', '필', '동방', '두', '근', '묵', '미', '요', '야', '환', '옹', '호', '만', '운', '자', '창', '탄', '사', '종', '포', '곡', '단', '범', '순', '순', '엽', '영', '돈', '애', '부', '학', '수', '춘', '개', '십', '후', '뇌', '영', '비', '수', '난', '운', '초', '군', '어금', '준', '담', '내', '묘', '장곡', '초', '교', '영', '저', '삼', '강전', '후', '단', '순', '누', '소봉', '돈', '뇌', '원', '즙', '증', '망절', '빙', '삼', '우', '증', '경', '소', '예']
popname_spell = ['가', '각', '간', '갈', '감', '갑', '강', '개', '객', '갱', '갹', '거', '건', '걸', '검', '겁', '게', '격', '견', '결', '겸', '경', '계', '고', '곡', '곤', '골', '공', '곶', '과', '곽', '관', '괄', '광', '괘', '괴', '굉', '교', '구', '국', '군', '굴', '궁', '권', '궤', '귀', '규', '균', '귤', '극', '근', '글', '금', '급', '긍', '기', '긴', '길', '김', '나', '낙', '난', '날', '남', '납', '낭', '내', '냉', '녀', '년', '념', '녕', '노', '녹', '논', '농', '뇌', '뇨', '누', '눈', '눌', '뉴', '늑', '늠', '능', '니', '닉', '다', '단', '달', '담', '답', '당', '대', '댁', '덕', '도', '독', '돈', '돌', '동', '두', '둔', '둘', '득', '등', '라', '락', '란', '랄', '람', '랑', '래', '랭', '략', '량', '려', '력', '련', '렬', '렴', '렵', '령', '례', '로', '록', '론', '롱', '뢰', '료', '룡', '루', '류', '륙', '륜', '률', '륭', '륵', '름', '릉', '리', '린', '림', '립', '마', '막', '만', '말', '망', '매', '맥', '맹', '멱', '면', '별', '명', '몌', '모', '목', '몰', '몽', '묘', '무', '묵', '문', '물', '미', '민', '밀', '박', '반', '발', '방', '배', '백', '번', '벌', '범', '법', '벽', '변', '별', '병', '보', '복', '본', '볼', '봉', '부', '북', '분', '불', '붕', '비', '빈', '빙', '사', '삭', '산', '살', '삼', '삽', '상', '새', '색', '생', '서', '석', '선', '설', '섬', '섭', '성', '세', '소', '속', '손', '솔', '송', '쇄', '쇠', '수', '숙', '순', '술', '숭', '슬', '습', '승', '시', '식', '신', '실', '심', '십', '아', '악', '안', '알', '암', '압', '앙', '애', '액', '앵', '야', '약', '양', '어', '억', '언', '얼', '엄', '업', '엔', '여', '역', '연', '열', '염', '영', '예', '오', '옥', '온', '올', '응', '와', '완', '왈', '왕', '왜', '외', '요', '욕', '용', '우', '욱', '운', '을', '웅', '원', '월', '위', '유', '육', '윤', '율', '은', '을', '음', '읍', '응', '의', '이', '익', '인', '일', '임', '입', '잉', '자', '작', '잔', '잠', '잡', '장', '재', '쟁', '저', '적', '전', '절', '점', '접', '정', '제', '조', '족', '존', '졸', '종', '좌', '죄', '주', '죽', '준', '줄', '중', '즉', '즙', '증', '지', '직', '진', '질', '짐', '집', '징', '차', '착', '찬', '찰', '참', '창', '채', '책', '처', '척', '처', '철', '처', '척', '천', '철', '첨', '접', '청', '체', '초', '촉', '촌', '총', '촬', '최', '추', '축', '춘', '출', '충', '췌', '취', '측', '층', '치', '칙', '친', '칠', '침', '칩', '칭', '쾌', '타', '타', '탄', '탈', '탐', '탕', '태', '택', '탱', '터', '토', '통', '되', '투', '특', '틈', '파', '판', '팔', '패', '팽', '퍅', '편', '폄', '평', '폐', '포', '폭', '표', '품', '풍', '피', '필', '핍', '하', '학', '한', '할', '함', '합', '항', '해', '액', '행', '향', '허', '헌', '헐', '엄', '역', '현', '혈', '험', '협', '형', '혜', '호', '혹', '혼', '홀', '홍', '화', '확', '환', '활', '황', '회', '획', '횡', '효', '후', '훈', '훙', '훤', '훼', '휘', '휴', '휼', '흉', '흔', '흘', '흠', '흡', '흥', '희', '힐', '끽', '쌍', '씨']

471

In [6]:
len(kr_sungdb)

288

In [5]:
len(popname_spell)

471

In [47]:
def name_gen():
    name_xx=''
    name_xx= name_xx + kr_sungdb[random.randint(0,287)]
    name_xx= name_xx + popname_spell[random.randint(0,470)]
    name_xx= name_xx + popname_spell[random.randint(0,470)]
    return name_xx

In [48]:
names = [ name_gen() for i in range(50)]

In [49]:
print(names)

['정양괴', '탄욱늠', '순봉접', '차부익', '제포교', '양길겁', '백날번', '차변객', '동력농', '낭례쇄', '자끽토', '화박폐', '구뇨직', '어액눈', '염면훈', '남향객', '설향쌍', '동방생협', '천새작', '십륭중', '원철길', '원슬뉴', '염벽향', '위농낙', '교훈철', '범환함', '동방물종', '돈붕조', '빈산곤', '섭근훈', '유락종', '방되흠', '김량긍', '전빈위', '아계둘', '모볼련', '진얼청', '시혹갈', '소달혈', '영어객', '강전혈형', '채감댁', '윤액핍', '진혜획', '채낭속', '소아득', '환핍존', '장씨타', '서문청겁', '복철실']

In [51]:
names = [ name_gen() for i in range(10)]
weights = [random.randint(45,101) for xx in names]
heights = [random.randint(150,221) for xx in names]

In [55]:
BMI= pd.DataFrame({
    "이름" : names,
    "몸무게" : weights,
    "키" : heights
})

In [56]:
BMI

    이름  몸무게    키
0  유무편   47  164
1  반병흉   84  181
2  도야별   90  190
3  저번양   91  193
4  피본연   56  210
5  장명양   54  175
6  소율란   65  170
7  나친락   96  167
8  탄임모   68  164
9  미갈훈   62  158

In [59]:
#BMI_index = 몸무게/(키/100) **2
BMI["BMI_index"] = BMI.몸무게/(BMI.키/100) ** 2

In [60]:
BMI

    이름  몸무게    키  BMI_index
0  유무편   47  164  17.474717
1  반병흉   84  181  25.640243
2  도야별   90  190  24.930748
3  저번양   91  193  24.430186
4  피본연   56  210  12.698413
5  장명양   54  175  17.632653
6  소율란   65  170  22.491349
7  나친락   96  167  34.422174
8  탄임모   68  164  25.282570
9  미갈훈   62  158  24.835763

In [61]:
BMI.round(decimals=2)

    이름  몸무게    키  BMI_index
0  유무편   47  164      17.47
1  반병흉   84  181      25.64
2  도야별   90  190      24.93
3  저번양   91  193      24.43
4  피본연   56  210      12.70
5  장명양   54  175      17.63
6  소율란   65  170      22.49
7  나친락   96  167      34.42
8  탄임모   68  164      25.28
9  미갈훈   62  158      24.84

In [64]:
def health_info(h_idx):
    if h_idx < 20:
        return '저체중'
    elif h_idx >= 20 and h_idx <= 24:
        return '정상'
    elif h_idx > 24 and h_idx <= 29:
        return '과체중'
    else:
        return '비만'

In [69]:
BMI['BMI결과'] = [health_info(xx) for xx in BMI.BMI_index]
# 이런 방식도 있는데 더 권장하는 방법이 있다
# 안되는건 아닌데

In [71]:
BMI.rename(columns={'BMI결과':'BMI결과1'}, inplace=True)

In [73]:
BMI['BMI결과2'] = BMI['BMI_index'].apply(health_info)
# mapping과 비슷하여 가장 처리속도가 빠르다
# map 과 lambda는 거의 동급 속력

In [74]:
BMI

    이름  몸무게    키  BMI_index BMI결과1 BMI결과2
0  유무편   47  164  17.474717    저체중    저체중
1  반병흉   84  181  25.640243    과체중    과체중
2  도야별   90  190  24.930748    과체중    과체중
3  저번양   91  193  24.430186    과체중    과체중
4  피본연   56  210  12.698413    저체중    저체중
5  장명양   54  175  17.632653    저체중    저체중
6  소율란   65  170  22.491349     정상     정상
7  나친락   96  167  34.422174     비만     비만
8  탄임모   68  164  25.282570    과체중    과체중
9  미갈훈   62  158  24.835763    과체중    과체중

In [77]:
BMI['BMI결과3'] = BMI.apply(lambda x: health_info(x["BMI_index"]), axis=1)
#여러개의 col 또는 index를 이용하고싶을때 이런 방법을 사용한다

In [78]:
BMI

    이름  몸무게    키  BMI_index BMI결과1 BMI결과2 BMI결과3
0  유무편   47  164  17.474717    저체중    저체중    저체중
1  반병흉   84  181  25.640243    과체중    과체중    과체중
2  도야별   90  190  24.930748    과체중    과체중    과체중
3  저번양   91  193  24.430186    과체중    과체중    과체중
4  피본연   56  210  12.698413    저체중    저체중    저체중
5  장명양   54  175  17.632653    저체중    저체중    저체중
6  소율란   65  170  22.491349     정상     정상     정상
7  나친락   96  167  34.422174     비만     비만     비만
8  탄임모   68  164  25.282570    과체중    과체중    과체중
9  미갈훈   62  158  24.835763    과체중    과체중    과체중